[build]
command = "npm run build"
publish = "dist"
functions = "src/functions"  # Si usas funciones serverless (opcional)

[context.production.environment]
NODE_VERSION = "18"  # Usa la misma versión que localmente