backend:
  name: git-gateway
  branch: main

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "promociones"
    label: "Promociones"
    folder: "src/content/promociones"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}
  - name: "config"
    label: "Configuraciones"
    files:
      - label: "General"
        name: "general"
        file: "src/content/configuracion/general.json"
        fields:
          - {label: "Nombre del sitio", name: "siteName", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}

