# public/admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "promociones"
    label: "Promociones"
    folder: "src/content/promociones"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Descripción", name: "description", widget: "text"}
