backend:
  name: github
  repo: 4l4nGomez/Lavo-Plus  # ⚠️ Pon aquí tu repo exacto
  branch: main
  auth_scope: repo
  base_url: https://lavoplus.netlify.app
  auth_endpoint: https://github.com/login/oauth/authorize
  client_id: Ov23liBDKvkwzEDbZ3Nc

media_folder: "public"
public_folder: "/"

collections:
  - name: "promociones"
    label: "Promociones"
    folder: "src/content/promociones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
