backend:
  name: git-gateway
  branch: main # o la rama principal de tu repo

media_folder: "public"
public_folder: "/"

collections:
  - name: "home"
    label: "Página de Inicio"
    folder: "src/content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
