backend:
  name: github
  repo: 4l4nGomez/Lavo-Plus  # 👈 Cambia esto a tu repo real
  branch: main
  site_domain: lavoplus.netlify.app

media_folder: "public"
public_folder: "/"

editor:
  preview: false

collections:
  - name: "promociones"
    label: "Promociones"
    folder: "src/content/promociones"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Fecha"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm"
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: false
      - label: "Contenido"
        name: "body"
        widget: "markdown"
