backend:
  name: git-gateway
  branch: main  # O la rama principal que uses (master/main)

media_folder: "public/img" # Donde se subirán las imágenes
public_folder: "/img"

collections:
  - name: "promociones"
    label: "Promociones"
    folder: "src/content/promociones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image" }
